### ISSUE TITLE
Questions on release action

### ISSUE THREAD

**Issue by jwodder** [datalad/release-action#2]
@yarikoptic 

* Should the action include building a Python package and uploading to PyPI?  Should this be optional?
* DataLad's release procedure includes running `make update-changelog` after `scriv collect` and before committing & tagging; how should the action handle this while still being generic enough for use by other projects?
* Currently, the action only ever bumps the patch (third) component of the version; until #1 is implemented, what (if anything) should cause the minor or major component to be incremented?

**Comment by yarikoptic** [comment]
> @yarikoptic
> 
> * Should the action include building a Python package and uploading to PyPI? 

yes

> Should this be optional?

ATM I do not see the need for optional, but I would welcome if it is (with default "auto" build/upload to pypi if there is `setup.py`) - then I could use that action for non-python projects e.g. git-annex-remote-rclone . 

> * DataLad's release procedure includes running `make update-changelog` after `scriv collect` and before committing & tagging; how should the action handle this while still being generic enough for use by other projects?

since I think we do not do that anywhere else - not worth some dedicated option. Let's add following generic options:
- `apt-depends` and `pip-depends`: list of packages to install extra depends via apt or pip
- `pre-tag`: text field to add commands to run right before tagging. It will be the 
```yaml
   pre-tag: |
          make update-changelog
          git add docs/source/changelog.rst
          git commit -m '[skip ci] Update CHANGELOG'
```
for the datalad core repo.

> * Currently, the action only ever bumps the patch (third) component of the version; until [config: be able to configure release level by branch #1](https://github.com/datalad/release-action/issues/1) is implemented, what (if anything) should cause the minor or major component to be incremented?

as in `auto` - should be based on github labels (can we do that?).  Configuration could be provided right there in the action configuration for which labels, if non-standard, should be used (what was in `.autorc`).  If #1 is implemented as part of the initial solution, then there would be no need for custom mapping in datalad core workflow.

**Comment by yarikoptic** [comment]
> > `apt-depends` and `pip-depends`: list of packages to install extra depends via apt or pip
> 
> What exactly is the benefit of having the action install these instead of having the workflow that calls the action install them?

you might be right - no benefit really 

> Also note that the final action may or may not run the Python script inside a virtualenv, which would complicate management of extra pip dependencies.

I guess it could expose `DATALAD_RELEASE_VENV_ACTIVATE` or alike, so if needed `source "$DATALAD_RELEASE_VENV_ACTIVATE"` could be used in `pre-tag` to "activate" that virtualenv.

**Comment by jwodder** [comment]
@yarikoptic Regarding running the Python script inside a virtualenv, I meant that the `datalad_release_action` script would get its own virtualenv with its dependencies installed inside.  If the pre-tag step is invoked by `datalad_release_action` directly (as opposed to being invoked by the action flow), then the pre-tag commands would run inside that virtualenv, which isn't very desirable.  I'm not entirely sure what you're referring to with `DATALAD_RELEASE_VENV_ACTIVATE`; are you saying that extra pip dependencies for the pre-tag step should be installed in a second virtualenv?

**Comment by jwodder** [comment]
@yarikoptic 

> it would encapsulate all needed steps for release within the config and thus allow to run locally

Are you saying that you want the Python code in `datalad_release_action` to run all the steps of the actions rather than having the Python code only run the parts that can't be easily run in Bash?  Note that [you previously said](https://github.com/datalad/release-action/issues/3#issuecomment-1267218817) that the Git author details should be configured at the action level rather than in the config file; moreover, the GitHub and PyPI tokens should not be set via the config file and should only be set via action inputs.
